
<div class="map">
	<h1>WE ARE HERE</h1>
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1281.8932298397026!2d36.22308692027343!3d50.015357519873554!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4127a1249e98c155%3A0x35f143088d42542a!2z0LLRg9C7LiDQkdCw0LrRg9C70ZbQvdCwLCA0LCDQpdCw0YDQutGW0LIsINCl0LDRgNC60ZbQstGB0YzQutCwINC-0LHQu9Cw0YHRgtGM!5e0!3m2!1sru!2sua!4v1450529811652" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
<div class="contact_us">
	<h1>CONTACT US</h1>
	<form action="" method="post" id="" class="form">
		<div class="field">
			<label for="fldName" >Name<span class="requiredfld">*</span></label>
			<input type="text" id="fldName" name="name" class="text">
		</div>
		<div class="field">
			<label for="fldEmail">Email<span class="requiredfld">*</span></label>
			<input type="text" id="fldEmail" name="email" class="text">
		</div>
		<div class="field">
			<label for="fldPhone">Phone</label>
			<input type="text" id="fldPhone" name="phone" class="text">
		</div>
		<div class="field">
			<label for="fldDescription">Description<span class="requiredfld">*</span></label>
			<textarea type="text" class="text" id="fldDescription" name="description" cols="20" rows="10" placeholder="Put you message down here"></textarea>
		</div>	
		<div class="sub">
			<input type="submit" id="fldSubmit" name="submit" value="SEND">
		</div>		
	</form>
</div>