<div class="contact_us">
	<h1>CONTACT US</h1>
	<form action="" method="post" id="" class="form">
		<div class="field">
			<label for="fldName" >Name<span class="requiredfld">*</span></label>
			<input type="text" id="fldName" name="name" class="text">
		</div>
		<div class="field">
			<label for="fldEmail">Email<span class="requiredfld">*</span></label>
			<input type="text" id="fldEmail" name="email" class="text">
		</div>
		<div class="field">
			<label for="fldPhone">Phone</label>
			<input type="text" id="fldPhone" name="phone" class="text">
		</div>
		<div class="field">
			<label for="fldDescription">Description<span class="requiredfld">*</span></label>
			<textarea type="text" class="text" id="fldDescription" name="description" cols="20" rows="10" placeholder="Put you message down here"></textarea>
		</div>	
		<div class="sub">
			<input type="submit" id="fldSubmit" name="submit" value="SEND">
		</div>		
	</form>
</div>