<div id="slider">
	<ul>
		<li><a href="http://magento.first.test/index.php/ginger-cat.html"><img src="http://magento.first.test/media/ainstainer/1.jpg"></a></li>
		<li><a href="http://magento.first.test/index.php/tiger-cub.html"><img src="http://magento.first.test/media/ainstainer/2.jpg"></a></li>
		<li><a href="http://magento.first.test/index.php/puma.html"><img src="http://magento.first.test/media/ainstainer/3.jpg"></a></li>
	</ul>
</div>